### ISSUE TITLE
Consider installing devDependencies by default

### ISSUE THREAD

**Issue by jmorrell** [heroku/heroku-buildpack-nodejs#431] opened 2017-06-13 18:02 UTC
Pro: Many users getting started with Heroku try to run a build step with `webpack`, `gulp`, etc only to find that it's in their `devDependencies` and not installed by default on Heroku. They then have to figure out how to tell Heroku to install these. Defaulting to installing everything makes for a smoother onboarding.

Con: Longer install times and larger slugs for existing large apps

First step: gather metrics

**Comment by edmorley** [comment] 2017-06-13 18:18
For users that don't commit build assets to their source directory (the better approach IMO), I see the building assets step as a production dependency, not a development dependency - which makes putting them in `devDependencies` a bug. After all, in development users will often not perform a full build at all and instead use a dev-server to dynamically serve assets.

An alternative to ease onboarding might be for the buildpack to check (on a non-zero return from the preinstall/postinstall/heroku-* `package.json` run scripts) whether the failed command is in `devDependencies`, and if so, output an appropriate message suggesting they use `dependencies` instead?

**Comment by jmorrell** [comment] 2017-06-13 18:52
@edmorley I don't necessarily disagree, but there is a big difference between what users *should* do, and what the actually do in practice. Checking in built assets has its own issues, and goes against established community best practices. We should meet people where they are when we can.

If a warning doesn't already exists I'm definitely for adding that, but I'd prefer for things to "just work" rather than make a non-trivial percentage of users either modify their app or set an environment variable to run on Heroku.

**Comment by edmorley** [comment] 2017-06-13 18:55
Reading back I can see it was ambiguous -- by "the better approach" I meant I prefer **not** committing assets. I don't for one minute think suggesting people change their workflow in that regard is practical :-)

**Comment by jmorrell** [comment] 2017-06-13 19:00
Oh, I see now. I don't think forcing people to put things under `dependencies` is the right solution if it hits a large % of users. I suspect it does, which is why I want to gather metrics.

The larger story is that frontend build errors are a huge % of the number of support tickets that we receive for Node, and anything we can do to make that process easier is a high priority for me.

**Comment by Cryptophobia** [comment] 2017-06-15 18:53
The right solution would be to not have to rely on the user to move to devDependencies to `dependencies` and to follow their current nodejs workflow. But installing `devDependencies` and `dependencies` together is also not the right approach because of testing frameworks / tools and other things that should not be installed as dependencies in production - `nodemon` and `forever`.

Why not just search for a new flag in the `package.json` file similar to how how `heroku-postbuild` works but call it something like `heroku-build-with-dev` or similar?

**Comment by jmorrell** [comment] 2017-06-15 22:29
@jasonkarns There are a couple of issues that I see there:

- It doesn't fit with the Heroku deploy model `git push heroku master`. It's not a good idea for us to say "deploy this way unless you're using Node, then use this other thing"
- apps that use Node + another platform
- native dependencies

but mainly we have 10's of thousands of existing apps using the current deploy process.

**Comment by jasonkarns** [comment] 2017-06-15 23:40
I don't understand why this wouldn't work. My intention is that all of the above would happen in the build pack and not have any impact on users (migration path may be necessary for some configurations, i'm unsure).

**Comment by jasonkarns** [comment] 2017-06-15 23:52
A better explanation:

after `git push heroku master`:

the buildpack does the git checkout of master, runs npm install _with devDeps_ (so app authors don't need to move devDeps to be prod deps). Then the buildpack runs npm-pack, generating the app tarball (with with all the compiled/built assets as per the `prepare` npm script). The app is now fully contained and ready to execute, less node_modules. All that's left is to run `npm install --production` to get the prod-only node_modules tree and you have you slug (packed app tarball+production node_modules).

**Comment by nickmccurdy** [comment] 2017-06-23 01:18
From the [`package.json` docs](https://docs.npmjs.com/files/package.json):

> Please do not put test harnesses or transpilers in your `dependencies` object. See [`devDependencies`](https://docs.npmjs.com/files/package.json#devdependencies).

For this reason, I disagree with [the devDependencies section of Heroku Node.js Support](https://devcenter.heroku.com/articles/nodejs-support#devdependencies). To follow npm's recommendations and avoid confusion, I think it would be better to either set `NPM_CONFIG_PRODUCTION=true` by default or build the source with `devDependencies` included in advance (as with @jasonkarns' suggestion of `npm pack`).

**Comment by fenduru** [comment] 2017-08-03 15:54
The way I see `dependencies` vs `devDependencies` is the difference between _runtime_ dependencies and _build time_ dependencies. For instance, if you are working on an NPM package and you list a transpiler in `dependencies` then every consumer of that package will pull in the transpiler even though their is no need. I do not think there is a fundamental difference between typical NPM pacakges and those being deployed via Heroku.

**Comment by nickmccurdy** [comment] 2017-08-03 16:29
I agree, as long as you can treat libraries only used on the client side as build time dependencies because a bundler is inlining them for you.

**Comment by jmorrell** [comment] 2017-08-03 16:41
> invoking npm install --production after a full npm install has already populated the node_modules directory (with devDeps) will simply prune all the dev Deps away.

If this is quick even for large dependency trees then it sounds like a great solution 👍

**Comment by nickmccurdy** [comment] 2017-08-03 17:15
That sounds good, the `--production` flag could just be toggled in an env variable or something like that.

**Comment by bbatha** [comment] 2017-08-03 17:18
Instead of doing the whole install, pack, reinstall workflow. Maybe it should just run `npm prune --production`?

**Comment by jasonkarns** [comment] 2017-08-03 17:35
@bbatha at what point? without a non-production install, what would be getting pruned?

how would the app get built? (ie, the babel compilation, etc) this is done automatically by npm-pack via the `prepare` hook that npm invokes.

**Comment by nickmccurdy** [comment] 2017-08-03 17:42
Also, I could be wrong but I think `--production` sets `NODE_ENV` to `production`, not doing this (including using prune) could break production builds or enable dangerous development features in production.

**Comment by jasonkarns** [comment] 2017-08-03 18:00
@nickmccurdy 

> --production sets NODE_ENV to production

Nope. Neither `npm install` nor `npm prune` mutate your environment.

**Comment by jasonkarns** [comment] 2017-08-03 18:04
Well, I should clarify. It sets `NODE_ENV=production` _during the install_. But that doesn't affect runtime.

An example package with a postinstall script: `echo node_env: $NODE_ENV`

```
$ echo node_env: $NODE_ENV && npm install --production && echo node_env: $NODE_ENV
node_env:

> prod@0.0.0 postinstall /private/tmp/prod
> echo node_env: $NODE_ENV

node_env: production
npm WARN prod@0.0.0 No description
npm WARN prod@0.0.0 No repository field.

up to date in 0.118s
node_env:
```

**Comment by fenduru** [comment] 2017-08-03 18:05
> @bbatha at what point? without a non-production install, what would be getting pruned?

This is just an alternative to using `npm pack` and then having to run `npm install` a second time (why install things that were already installed moments ago?). This would install everything (including `devDependencies`) first, then run the build script, then prune out the no longer necessary `devDependencies`.

**Comment by nickmccurdy** [comment] 2017-08-03 18:13
@jasonkarns I agree that it doesn't affect runtime *directly*, but if a build tool behaves differently in production (webpack often does depending on its configuration), the code and dependencies may be different at runtime in ways that affect performance, security, stability, etc.

**Comment by jasonkarns** [comment] 2017-08-03 18:17
running npm install twice doesn't actually install anything twice. It builds the virtual dep tree in memory and then ensures that the filesystem matches it. Running npm-prune is functionally equivalent.

So `npm i; npm pack; npm prune --production` would be the same as running `npm i; npm pack; npm i --production`. (I personally have less confidence in prune working as intended due to npm's history, which is why I originally suggested install. But these days, I guess I'd trust it. :) )

I was thrown off by the comment that "prune" could replace "install, pack, reinstall".

> Instead of doing the whole install, pack, reinstall workflow. Maybe it should just run npm prune --production?

The first install (with devDeps) is obviously still necessary such that devDeps exist in order to build the app. The pack step is necessary to compile the app while devDeps are available. So, a more accurate interpretation of that comment is that "prune" just replaces the last "reinstall". Which I'll concede.

`npm i && npm pack && npm prune --production`

**Comment by bbatha** [comment] 2017-08-03 18:20
> I was thrown off by the comment that "prune" could replace "install, pack, reinstall".

Sorry if that's  unclear. What I meant is that install, pack and then prune can be just install then prune. There's no need for the pack step unless your going to upload the built package somewhere else to npm or from CI system as a built slug.

**Comment by nickmccurdy** [comment] 2017-08-03 18:20
To clarify, those two sets of commands are only the same if your build tools executed in `npm install` behave the same in production.

**Comment by jasonkarns** [comment] 2017-08-03 18:26
> There's no need for the pack step

@bbatha heroku would need to run the compilation step, regardless. having heroku specify some custom-to-heroku npm script as the build step is inferior to using the conventional (and established norm) of using `prepare`. And since heroku needs to make a slug _anyway_ of the compiled assets, running npm-pack does the compilation *and* zipping in one go. Further, npm-pack would respect the package's rules about which files get included in the tarball. Authors would then be in control of whether unit tests and examples and docs, for instance, are included in the slug. This would lead to smaller slugs, and keep heroku in-line with how npm uses pack for publishing.

@nickmccurdy There shouldn't _be_ any build tools being executed during npm-install.

**Comment by nickmccurdy** [comment] 2017-08-03 18:32
That's cool, I didn't know `npm pack` ran `prepare`. 👍 for this.

I was implying that `npm install` runs hook scripts like `prepare`, not that the internal install command calls special scripts directly. `npm install` under the latest version of npm triggers `prepare` automatically. Sorry if that was unclear.

**Comment by jasonkarns** [comment] 2017-08-03 18:42
@nickmccurdy Ah! Okay! Now I get you. 👍 thanks for being patient while I caught up :)

So yeah, in that case, I suppose the `--production` flag could impact the build tools! I'm not certain how I feel about build tools knowing/caring about `NODE_ENV`. Though if they _do_ alter behavior, `production` is what we'd want. So the compilation triggered by the first npm-install is probably undesirable. I'd still _prefer_ to use npm-pack because of how it specifically includes only the necessary (specified) files in the final tarball. But I suppose this would mean that:

`npm i && npm pack && npm prune --production` would actually execute the `prepare` script twice :(

**Comment by fenduru** [comment] 2017-08-03 18:53
@jasonkarns it is not uncommon for build tools to alter behavior based on `NODE_ENV`, [as seen here](https://webpack.js.org/guides/production/#node-environment-variable)

**Comment by bbatha** [comment] 2017-08-03 18:54
> @bbatha heroku would need to run the compilation step, regardless. having heroku specify some custom-to-heroku npm script as the build step is inferior to using the conventional (and established norm) of using prepare. And since heroku needs to make a slug anyway of the compiled assets, running npm-pack does the compilation and zipping in one go. Further, npm-pack would respect the package's rules about which files get included in the tarball. Authors would then be in control of whether unit tests and examples and docs, for instance, are included in the slug. This would lead to smaller slugs, and keep heroku in-line with how npm uses pack for publishing.


Most of the logic here is sound for running pack. 👍 for reusing existing specification mechanisms. However, I don't really see how `pack` fits in the buildpack. If you're in a run of the buildpack, running `pack` would necessitate wiping the local directory, unzipping the zip and then running npm install. Then rezipping the whole thing. This seems to duplicate quiet a lot of work for little gain. Running `prepare` directly might be the right semantics you want inside of the buildpack's execution environment.

If your someone who builds on CI and uploads the slug to heroku. `npm pack` is a better fit, however it would not include the `node_modules` directory so you'd still need to run a buildpack to run `NPM_CONFIG_PRODUCTION=false npm install`. And as far as I know its not possible to have heroku run a buildpack on an uploaded slug like that.

The third thing running pack in the directory doesn't really account for is the multi-buildpack case where you may also want to include other directories in the slug that aren't listed in your `package.json`. This is also an issue if you want to defer cleanup until the end of all your buildpacks. The later is also an issue for running `npm prune --production`.

**Comment by jasonkarns** [comment] 2017-08-03 18:58
Yeah, my original suggestion would have resulted in two tarballs that the buildpack would need to handle: the npm-packed tarball, and the node_modules directory itself. Not as clean as just having a single tarball, but I was thinking that two would be easily managed.

Re: multi-buildpacks. I wasn't even thinking about those. Good call.

**Comment by nickmccurdy** [comment] 2017-08-03 19:15
That's unfortunate, should we avoid pack then or is there a way to get it to work with multiple buildpacks?

**Comment by Ajaxy** [comment] 2018-02-09 12:19
Is there any suggestion as a result of this topic?
I'd love to: 
1) Install dev deps
2) Run my build script with `npm run build`
3) Save built app without dev deps

**Comment by jasonkarns** [comment] 2018-02-09 15:18
@Ajaxy (quick random tidbit: `prepare` script is run automatically as part of install, so it's generally recommended to have prepare be your "build" script. or at least to have `"prepare": "npm run build"`)

**Comment by jmorrell** [comment] 2018-02-09 17:15
@Ajaxy I'm afraid other work has taken priority, but I'll be working on a PR next week that will make that the default

In the mean time you could run `npm prune --production` as part of your `heroku-postbuild` script

**Comment by Ajaxy** [comment] 2018-02-09 18:20
Thanks, so I ended up with:

```js
...
    "build": "babel src -d build",
    "deploy:staging": "git push heroku master -f",
    "deploy:production": "heroku pipelines:promote",
    "prepare": "npm run build",
    "heroku-postbuild": "npm prune --production"
...
```

**Comment by Ajaxy** [comment] 2018-02-09 18:28
Also, it seems that if I add `src` folder to `.slugignore` then I'm not able to build, so I had to change the last one for: `"heroku-postbuild": "npm prune --production && rm -rf ./src"`

**Comment by jmorrell** [comment] 2018-02-09 18:39
@Ajaxy I would recommend doing everything in `heroku-postbuild`:

```
"heroku-postbuild": "npm run build && npm prune --production"
```

In the next few months I'm going to try to implement a solution to https://github.com/heroku/heroku-buildpack-nodejs/issues/479 which will run `build` by default unless `heroku-postbuild` is defined

**Comment by Ajaxy** [comment] 2018-02-09 19:34
It hasn't worked for me. 

> remote: -----> Building dependencies
remote:        Installing node modules (yarn.lock)
remote:        yarn install v1.4.0
remote:        [1/4] Resolving packages...
remote:        success Already up-to-date.
remote:        Done in 1.08s.
remote:        Running heroku-postbuild (yarn)
remote:        yarn run v1.4.0
remote:        $ npm run build && npm prune --production && rm -rf src
...
Error: Cannot find module 'babel-runtime/core-js/object/keys'

So seems dev packages are not installed.
If I move `npm run build` back to `"prepare"`, then it does install dev packages again:

> remote: -----> Building dependencies
remote:        Installing node modules (yarn.lock)
remote:        yarn install v1.4.0
remote:        [1/4] Resolving packages...
remote:        [2/4] Fetching packages...
...
remote:        [3/4] Linking dependencies...
...
remote:        [4/4] Building fresh packages...
remote:        $ npm run build
...
remote:        Done in 29.02s.
remote:        Running heroku-postbuild (yarn)
remote:        yarn run v1.4.0
remote:        $ npm prune --production && rm -rf src
remote:        removed 426 packages in 5.632s
remote:        Done in 6.21s.

**Comment by Ajaxy** [comment] 2018-02-09 20:08
Well, it seems the last one was some unrelated issue. Now it's gone.

Also, for those using `yarn`: according to this topic https://github.com/yarnpkg/yarn/issues/696 you need to use
```
yarn install --production --ignore-scripts --prefer-offline
```
instead of
```
npm install --production
```

**Comment by lirbank** [comment] 2018-02-20 19:51
@jmorrell I just noticed that setting `heroku-postbuild` to `yarn build && yarn --production` or `yarn build && yarn --production && rm -fR ./src` won't work if you're using Heroku CI. The tests will fail since the dev deps are not there (where you'd typically have your test runners etc).

Figured I'd mention it for consideration when you work on #519

**Comment by jmorrell** [comment] 2018-02-20 21:48
@lirbank I think in that case you can check the value of the `$CI` environment variable and add a condition. Something like this:

```
yarn build && [ $CI <> true ] && yarn --production && rm -fR ./src
```

In #519 I'll be sure to do the reasonable thing in [`test-compile`](https://github.com/heroku/heroku-buildpack-nodejs/blob/master/bin/test-compile). I've added a new bullet point for that. Thanks for calling this out 👍

**Comment by lirbank** [comment] 2018-02-20 22:56
Quick update, for anyone interested, here is my final solution that works with Heroku CI too:

```
"heroku-postbuild": "yarn build && test \"$CI\" != \"true\" && yarn --production --ignore-scripts --prefer-offline"
```

**Closed** 2018-03-01 01:04 UTC
