### ISSUE TITLE
Build process fails when package-lock.json is added on an existing application

### ISSUE THREAD

**Issue by openjck** [heroku/heroku-buildpack-nodejs#425] opened 2017-06-09 03:48 UTC
I always try to provide straightforward steps to reproduce in the issues I file, but this one is a little more tricky. I'm unable to reproduce this locally or on a new Heroku application; at the moment it only affects a staging application I contribute to.

The Node build process fails on our application when the *package-lock.json* file is present. When the file is removed, the build process succeeds. I would chalk this up to version discrepancies, but again, I can't reproduce the issue locally or on a new Heroku application even when *package-lock.json* is present.

Relevant files:

* [package.json](https://github.com/mozilla/experiments-viewer/blob/2796e15fd572ef6765f3c690ac5200530e3b0514/package.json)
* [package-lock.json](https://github.com/mozilla/experiments-viewer/blob/2796e15fd572ef6765f3c690ac5200530e3b0514/package-lock.json)
* [gulpfile.babel.js](https://github.com/mozilla/experiments-viewer/blob/2796e15fd572ef6765f3c690ac5200530e3b0514/gulpfile.babel.js)

Build output:

```


-----> Node.js app detected

-----> Creating runtime environment

       

       NPM_CONFIG_LOGLEVEL=error

       NPM_CONFIG_PRODUCTION=true

       NODE_VERBOSE=false

       NODE_ENV=production

       NODE_MODULES_CACHE=true

-----> Installing binaries

       engines.node (package.json):  unspecified

       engines.npm (package.json):   >=5.0.0

       

       Resolving node version 6.x via semver.io...

       Downloading and installing node 6.11.0...

       Resolving npm version >=5.0.0 via semver.io...

       Downloading and installing npm 5.0.3 (replacing version 3.10.10)...

-----> Restoring cache

       Loading 2 from cacheDirectories (default):

       - node_modules

       - bower_components (not cached - skipping)

-----> Building dependencies

       Installing node modules (package.json)

       

       > viewer@ postinstall /tmp/build_05317a4d9f86cbb0a9cf2739e8dd7aa9/mozilla-experiments-viewer-2796e15

       > gulp build

       

       module.js:471

       throw err;

       ^

       

       Error: Cannot find module 'safe-buffer'

       at Function.Module._resolveFilename (module.js:469:15)

       at Function.Module._load (module.js:417:25)

       at Module.require (module.js:497:17)

       at require (internal/module.js:20:19)

       at Object.<anonymous> (/tmp/build_05317a4d9f86cbb0a9cf2739e8dd7aa9/mozilla-experiments-viewer-2796e15/node_modules/readable-stream/lib/_stream_readable.js:32:36)

       at Module._compile (module.js:570:32)

       at Object.Module._extensions..js (module.js:579:10)

       at Module.load (module.js:487:32)

       at tryModuleLoad (module.js:446:12)

       at Function.Module._load (module.js:438:3)

       npm ERR! code ELIFECYCLE

       npm ERR! errno 1

       npm ERR! viewer@ postinstall: `gulp build`

       npm ERR! Exit status 1

       npm ERR!

       npm ERR! Failed at the viewer@ postinstall script.

       npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

       

       npm ERR! A complete log of this run can be found in:

       npm ERR!     /app/.npm/_logs/2017-06-09T03_42_43_092Z-debug.log

-----> Build failed

       

       We're sorry this build is failing! You can troubleshoot common issues here:

       https://devcenter.heroku.com/articles/troubleshooting-node-deploys

       

       Some possible problems:

       

       - Node version not specified in package.json

       https://devcenter.heroku.com/articles/nodejs-support#specifying-a-node-js-version

       

       - A module may be missing from 'dependencies' in package.json

       https://devcenter.heroku.com/articles/troubleshooting-node-deploys#ensure-you-aren-t-relying-on-untracked-dependencies

       

       - This module may be specified in 'devDependencies' instead of 'dependencies'

       https://devcenter.heroku.com/articles/nodejs-support#devdependencies

       

       Love,

       Heroku

       

 !     Push rejected, failed to compile Node.js app.

 !     Push failed
```

Please feel free reach out to me privately if you need more detailed information about the application. I'm openjck on irc.mozilla.org and my email address is [that-same-username]@mozilla.com

**Comment by jmorrell** [comment] 2017-06-09 17:35
Would you mind opening up a ticket on help.heroku.com and asking them to escalate it to the Node team? I'll have more context on your application and maybe we can make a repro.

**Comment by openjck** [comment] 2017-06-09 18:28
Sure thing. I went ahead and opened ticket 484965. I'll let you decide whether you want to keep this GitHub issue open or not.

**Comment by jmorrell** [comment] 2017-06-16 16:34
Closing due to lack of ability to reproduce the error

**Closed by jmorrell** 2017-06-16 16:34 UTC

**Comment by WilliamNHarvey** [comment] 2017-07-23 02:49
this is still an existing error

**Comment by jmorrell** [comment] 2017-07-24 17:39
@WilliamNHarvey I'm afraid that unless this is reproducible it's not really actionable, and there's little help I can give you...

- update npm to `5.3.0`
- regenerate `package-lock.json`
- try switching stacks to [Heroku-16](https://devcenter.heroku.com/articles/heroku-16-stack#upgrading-an-app-to-heroku-16) or [Cedar-14](https://devcenter.heroku.com/articles/cedar-14-stack#upgrading-the-production-app-to-cedar-14), whichever your app isn't currently using
- switch to Yarn as a workaround

**Comment by joaoreynolds** [comment] 2017-08-08 13:32
For what it's worth, there is an issue on `npm` addressing this: https://github.com/npm/npm/issues/16839

Seems until the bug is fixed, the best thing is to either user `yarn` or remove `package-lock` from your project
