### ISSUE TITLE
Error "/usr/bin/jq: Permission denied"

### ISSUE THREAD

**Issue by overallduka** [heroku/heroku-buildpack-nodejs#856] opened 2020-11-05 12:35 UTC
I did have a error today when was deploying using this package in the latest version(v176):

```
=====> Downloading Buildpack: https://github.com/gaffneyc/heroku-buildpack-jemalloc.git
=====> Detected Framework: jemalloc
-----> jemalloc: Vendoring 5.2.1
-----> jemalloc: Building runtime environment
=====> Downloading Buildpack: https://github.com/heroku/heroku-buildpack-nodejs.git
=====> Detected Framework: Node.js
remote: /tmp/buildpackySeuL/lib/json.sh: line 5: /usr/bin/jq: Permission denied
remote: /tmp/buildpackySeuL/lib/json.sh: line 52: /usr/bin/jq: No such file or directory
remote:  !     Unable to parse package.json


-----> Build failed
```

Then I changed my buildpack url to use v174(https://github.com/heroku/heroku-buildpack-nodejs.git#v174) and it worked fine.

I did not tried v175 because was recently as well.

Just reporting to give a solution to others that might have the same error.

**Comment by effetmonstre** [comment] 2020-11-05 13:47
Thanks !
https://github.com/heroku/heroku-buildpack-nodejs.git#v175 worked fine for us ! :)

**Comment by danielleadams** [comment] 2020-11-05 13:59
@overallduka @effetmonstre can you use the `heroku/nodejs` buildpack? You can set it with `heroku buildpacks:set heroku/nodejs`.

**Comment by danielleadams** [comment] 2020-11-05 14:00
I'll look into this, looks like a bug on master for sure, but it's better to use the latest released buildpack version.

**Comment by danielleadams** [comment] 2020-11-05 14:10
@overallduka Can you give more information? I am not getting this bug when I use the master branch of the buildpack (`heroku buildpacks:set https://github.com/heroku/heroku-buildpack-nodejs.git`). 

What is happening after this?
```
=====> Downloading Buildpack: https://github.com/heroku/heroku-buildpack-nodejs.git
=====> Detected Framework: Node.js
```

How is `jq` trying to be accessed? We just swapped out jq to use what the stack image is using, but it should download it if its not present too (https://github.com/heroku/heroku-buildpack-nodejs/pull/854/files), so that would make it compatible with other stack images that may not have `jq`.

**Comment by rafalolszewski94** [comment] 2020-11-05 16:26
We're using `https://github.com/heroku/heroku-buildpack-nodejs.git` as main buildpack and it throws the same error.

**Comment by rauluranga** [comment] 2020-11-05 16:38
same for me!
yesterday i started seeing this issue
downgraded to **v175** and that worked fine for me.

```
-----> Cleaning up...
-----> Building jeep from herokuish...
-----> Adding BUILD_ENV to build environment...
-----> Warning: Multiple default buildpacks reported the ability to handle this app. The first buildpack in the list below will be used.
       Detected buildpacks: multi nodejs php
-----> Multipack app detected
=====> Downloading Buildpack: https://github.com/heroku/heroku-buildpack-nodejs
=====> Detected Framework: Node.js
remote: /tmp/buildpackwk1xz/lib/json.sh: line 5: /usr/bin/jq: Permission denied
remote: /tmp/buildpackwk1xz/lib/json.sh: line 52: /usr/bin/jq: No such file or directory
remote:  !     Unable to parse package.json


-----> Build failed

       We're sorry this build is failing! You can troubleshoot common issues here:
       https://devcenter.heroku.com/articles/troubleshooting-node-deploys

       If you're stuck, please submit a ticket so we can help:
       https://help.heroku.com/

       Love,
       Heroku
```

**Comment by overallduka** [comment] 2020-11-05 17:03
@danielleadams the log I had was pretty much what @rauluranga posted, I don't have much info other than I did tried deploy this morning and had this error.

I tried to create a bash file and execute this command:

```
JQ="/usr/bin/jq"
if ! test -f "$JQ"; then
  curl -Ls https://github.com/stedolan/jq/releases/download/jq-1.5/jq-linux64 > "/usr/bin/jq" \
      && chmod +x "/usr/bin/jq"
fi
```

And I had this error `file.sh: line 3: /usr/bin/jq: Operation not permitted`.

Surely is something related to permission.

**Comment by danielleadams** [comment] 2020-11-05 17:24
Just a question for anyone that's seeing this issue: is there a reason that you aren't referencing the buildpack through the buildpack registry, `heroku/nodejs`, instead of the GitHub url? That would be the same as using the `latest` released version, and `master` is more of an "edge", although it is usually stable. Unrelated to this bug, but since I have you all here, I'd like to understand. Thanks in advance.

**Comment by rauluranga** [comment] 2020-11-05 19:05
in my case is because im using [dokku](http://dokku.viewdocs.io/dokku/) for testing my projects, 
when you're using multiple buildpacks you should list them on a `.buildpacks` file.
i got the node-js buildpack url from their [docs](http://dokku.viewdocs.io/dokku~v0.11.0/deployment/methods/buildpacks/), thats why im using the github url.

**Comment by danielleadams** [comment] 2020-11-05 19:23
@rauluranga thanks! That helps a lot.

**Comment by topched** [comment] 2020-11-05 21:08
For us we are using the buildpack_url in gitlab, so its pointing right to the github as well. Downgrading to v175 worked for us

**Comment by danielleadams** [comment] 2020-11-05 21:36
fwiw, you should be able to use `v176`. `master` is not the same as `v176` or any versions. If you specify by URL, you're referencing `master` and not the latest release. I think what I am learning from this is maybe I need a `latest` tag that users using GitHub urls can use that correspond with the latest release. In this case, the latest release is `v176`.

**Comment by danielleadams** [comment] 2020-11-05 21:43
Is anyone experiencing this on Heroku? If not, which platform? Which operating system? I am unable to produce this issue on Heroku, so I need steps to reproduce so that I can see what's going on. We are granting executable access to the binary when it's installed (https://github.com/heroku/heroku-buildpack-nodejs/blob/41d6641ecf23582b0ae708f1940ab35c34eb5fdb/lib/json.sh#L5-L6), so I need to be able to understand why that doesn't seem to be working.

**Comment by danielleadams** [comment] 2020-11-05 22:15
@overallduka I hope you don't mind, but I renamed your Issue because it was misleading. The issue is on `master`, not on `v176` (as I explained above).

**Comment by EyeCode** [comment] 2020-11-06 13:18
> Is anyone experiencing this on Heroku? If not, which platform? Which operating system? I am unable to produce this issue on Heroku, so I need steps to reproduce so that I can see what's going on. We are granting executable access to the binary when it's installed, so I need to be able to understand why that doesn't seem to be working.

Dunno for heroku, but im using dokku with .buildpacks file to list this buildpack and got the error if i dont put the version number at the end of github url

**Comment by overallduka** [comment] 2020-11-06 14:08
Same as @EyeCode, I am using Dokku with .buildpacks file.

**Comment by edmorley** [comment] 2020-11-09 12:52
> We are granting executable access to the binary when it's installed, so I need to be able to understand why that doesn't seem to be working.
> 
> [](https://github.com/heroku/heroku-buildpack-nodejs/blob/41d6641ecf23582b0ae708f1940ab35c34eb5fdb/lib/json.sh#L5-L6)

The `/usr/bin` directory is not user-writable unless the compile is run as root. I've added some possible solutions to:
https://github.com/heroku/heroku-buildpack-nodejs/pull/854/files#r519781365

To anyone hitting this issue -- the underlying cause is that your Dokku base images don't have `jq` installed, and whilst the buildpack could choose to download jq as a temporary stop-gap, the better long term solution would be to update the Dokku base images to include `jq` (for parity with the Heroku stack images).

**Comment by danielleadams** [comment] 2020-11-09 16:15
A few things to note here:

1. I've created a `latest` tag. Please use this when referencing this buildpack if you want the most up-to-date releases when using the GitHub url.
2. @edmorley is correct, this seems like an issue with the Dokku platform. Heroku stack images provide `jq`, so per https://github.com/heroku/heroku-buildpack-nodejs/pull/854 we removed the dependency from the buildpack. Since Dokku seems to use a "herokuish" stack image, the stack image of the build probably needs to be updated.

Going to leave this open for a bit to give folks an opportunity to report if this resolves the issue.

**Comment by jesseshieh** [comment] 2020-11-11 20:16
Would it be possible to wait until herokuish has `jq` added before removing it here? Many users at Gigalixir are running into this issue as we use herokuish.

**Comment by danielleadams** [comment] 2020-11-12 15:47
Sure... I'll see how the issue progresses

**Comment by mladenoff** [comment] 2020-11-19 23:22
I am not on Dokku, but I have this same issue trying to deploy to Datica. 
The same issue in that `/usr/bin` isn't writable. Our image does seem to have `jq` in `/usr/local/bin`.
I don't know if Datica is using Herokuish, but they seem to be herokulike in some way (we are using Heroku buildpacks).
Do I just need to ask Datica to add `jq` into `/user/bin` one way or another?

**Comment by jesseshieh** [comment] 2020-11-20 17:05
Sorry to bug you guys, but we're still getting reports from customers saying this buildpack is broken. Is there a way to add jq back in just until herokuish is updated to include jq?

**Comment by josegonzalez** [comment] 2020-11-23 05:23
For anyone coming here because they are using either Herokuish or Dokku, I've released a new version of those.

That aside, these buildpacks are - very graciously! - provided by Heroku/Salesforce. As such, here is a bit of food for thought:

- Heroku customers: Ya'll should be all set, the Heroku folks make a best-in-breed platform and work real hard to make sure your use cases are taken care of.
- Gitlab customers: Go complain to Gitlab. I don't think they contribute back to the upstream projects (CNB, Herokuish, or Heroku's buildpacks) in any meaningful fashion (money, time, etc.).
- Dokku users: I actually caught this issue a while back but didn't have time to release a new version of Herokuish. `v0.5.20` was just released and should have an updated base image that pulls in JQ (our tests pass at least). Feel free to comment on gliderlabs/herokuish#617 if you still see issues.
- Herokuish users: If you're using Herokuish directly as part of your platform and making money from it, it probably makes sense for you all to contribute to either Herokuish or the underlying Buildpacks in some way. I'll leave you to sort out how you want to handle that, but OSS doesn't mean free labor.

Apologies to the NodeJS buildpack maintainers for the noise from Herokuish. Thank you for continuing your work, it is very much appreciated.

**Comment by danielleadams** [comment] 2020-11-30 19:45
Thanks for the explanation @josegonzalez and your work to get this fixed! Going to close this as there is a resolution now.

**Closed by danielleadams** 2020-11-30 19:45 UTC
Labels: platform issue
