### ISSUE TITLE
EROFS: read-only file system, access '/usr/local/bin'

### ISSUE THREAD

**Issue by hakunin** [heroku/heroku-buildpack-nodejs#468] opened 2017-09-06 08:59 UTC
Nothing in the app config changed and I am no longer able to deploy it this morning.

Tried making a new PR and the problem persists.

```
       [1/4] Resolving packages...
       [2/4] Fetching packages...
       [3/4] Linking dependencies...
       [4/4] Building fresh packages...
       success Saved lockfile.
       $ cd client && yarn install
       error An unexpected error occurred: "EROFS: read-only file system, access '/usr/local/bin'".
       info If you think this is a bug, please open a bug report with the information provided in "/tmp/build_511123d1db02c066ab30d1896704c2f5/<app>-13232ff7a068a478f642efc19a08bed3440fcfc9/yarn-error.log".
       info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
-----> Build failed
       
       We're sorry this build is failing! You can troubleshoot common issues here:
       https://devcenter.heroku.com/articles/troubleshooting-node-deploys
       
       Some possible problems:
       
       - This project was built with yarn, which is new and under development. Some projects can still be built more reliably with npm
       https://devcenter.heroku.com/articles/nodejs-support#build-behavior
       
       Love,
       Heroku
       
 !     Push rejected, failed to compile Node.js app.
 !     Push failed
```

**Comment by zharikovpro** [comment] 2017-09-06 09:25
We have the same issue. And [here's another guy](https://twitter.com/jan_joris/status/905342457285668865).

**Comment by idabmat** [comment] 2017-09-06 09:27
Same issue. I also noticed previous deploys used yarn 0.28.4, new ones are using 1.0.0 and resulting in the error above

**Comment by idabmat** [comment] 2017-09-06 09:28
Same issue. Noticed previous deploys were using yarn 0.28.4. New ones are using yarn 1.0.0 and causing the issue above

**Comment by edmorley** [comment] 2017-09-06 09:35
There's yarnpkg/yarn#4320 filed for this on Yarn's side, which points to the regression being caused by yarnpkg/yarn#3721. They've also opened yarnpkg/yarn#4322 to fix.

In the meantime an older version of yarn can be specified in the `engines.yarn` key, similar to the guide here for npm:
https://devcenter.heroku.com/articles/nodejs-support#specifying-an-npm-version

I wonder whether the nodejs buildpack should not use latest yarn when there is no `engines.yarn` key, but instead have a hardcoded "known safe" version that is periodically incremented? (Particularly now that it's reached v1)

**Comment by edmorley** [comment] 2017-09-06 09:44
> I wonder whether the nodejs buildpack should not use latest yarn when there is no engines.yarn entry, but instead have a hardcoded "known safe" version that is periodically incremented?

Or at least only use the stable release rather then release candidates. The Yarn homepage currently says:
> Stable: v0.27.5 • Release Candidate v1.0.0

**Comment by hakunin** [comment] 2017-09-06 09:50
@edmorley thanks for the solution!
For copy-pasters, add this to your package.json:
```
  "engines": {
    "yarn": "0.28.4"
  },
```

**Comment by ericnograles** [comment] 2017-09-06 13:01
Just parroting here, but also experienced this issue and thanks for the snippet @hakunin 👍 

Definitely lock down your versions of everything using `engines`!

**Comment by hunterloftis** [comment] 2017-09-06 14:01
Would someone running into this issue mind testing against the patch branch?

```
$ heroku buildpacks:set https://github.com/heroku/heroku-buildpack-nodejs#manual-yarn-version
$ git push heroku master
```

**Comment by edmorley** [comment] 2017-09-06 14:10
Using that branch fixed the issue for us, with the compile log showing yarn 0.28.4 being used as intended:

```
-----> Installing binaries
       ...
       Resolving yarn version 0.28.4...
       Downloading and installing yarn (0.28.4)...
       Installed yarn 0.28.4
```

**Comment by hunterloftis** [comment] 2017-09-06 14:12
Thanks @edmorley!

**Comment by ericnograles** [comment] 2017-09-06 14:14
@hunterloftis all good here too, thanks for the prompt fix!

![image](https://user-images.githubusercontent.com/6023705/30116687-395f35ec-92ec-11e7-86ad-274a14c2df43.png)

**Comment by hunterloftis** [comment] 2017-09-06 14:28
Resolved by #469 (released ~30s ago). Please let us know if you still run into this issue.

Manual testing & version bumping hasn't been a popular choice in node (since the versions change so quickly), but I agree we should try to lock to something other than "latest." Is a scrape of the yarn homepage the best data source, or does someone know of a good way to get metadata like "latest stable version of yarn?"

**Closed by hunterloftis** 2017-09-06 14:28 UTC

**Comment by edmorley** [comment] 2017-09-06 14:42
> Is a scrape of the yarn homepage the best data source, or does someone know of a good way to get metadata like "latest stable version of yarn?"

I was hoping it would be possible to just refer to what the website uses, however it's static and is updated by a bot whose data source is unknown:
https://github.com/yarnpkg/website/commit/c23f92e2f03446a48be214d817d31296a235d2df

Though the yarn maintainers might have a better suggestion, but one option would be to use the [GitHub releases](https://github.com/yarnpkg/yarn/releases) metadata, since it seems to consistently use the pre-release attribute correctly.

In fact, the GitHub API docs suggest that this endpoint would do exactly that (return latest excluding pre-release):
https://developer.github.com/v3/repos/releases/#get-the-latest-release

...though you'd need to watch out for API rate limiting, if this were performed at compile time (rather than by nodebin.herokai.com and then cached).

**Comment by edmorley** [comment] 2017-09-06 14:48
Sorry for the double post - but a reminder for anyone who switched to the `manual-yarn-version` buildpack branch above to test the fix... Now that it's merged, switch back the the stable release (or master) to avoid later breakage due to the PR branch being deleted. To do this, use:
`heroku buildpacks:set heroku/nodejs`

**Comment by hunterloftis** [comment] 2017-09-06 15:05
👍  for `heroku buildpacks:set heroku/nodejs`

The nodebin service will be responsible for resolution, so rate limiting shouldn't be an issue. What do you think @jmorrell?

**Comment by Daniel15** [comment] 2017-09-08 05:06
Hey @edmorley and @hunterloftis, you can use https://yarnpkg.com/latest-version to get the version number. This uses the exact same data source as the website, and is what the Yarn installation script uses along with all the other automation relating to Yarn releases (eg. the Chocolatey and Homebrew packages are updated as soon as this number is bumped).

**Comment by Daniel15** [comment] 2017-09-08 05:07
Hey @edmorley and @hunterloftis, you can use https://yarnpkg.com/latest-version to get the version number. This uses the exact same data source as the website, and is what the Yarn installation script uses along with all the other automation relating to Yarn releases (eg. the Chocolatey and Homebrew packages are updated as soon as this number is bumped).

https://yarnpkg.com/latest.tar.gz will also give you the tarball of the latest stable release.

Similarly, you can use https://yarnpkg.com/latest-rc-version and /latest-rc.tar.gz to get the latest RC, and http://nightly.yarnpkg.com/latest-version to get the latest nightly version number (if you like to live dangerously).

**Comment by edmorley** [comment] 2017-09-08 10:22
> https://yarnpkg.com/latest.tar.gz will also give you the tarball of the latest stable release.

I checked this file at the time, but I'm pretty sure it was giving me the release candidate (1.0.0) rather than what the website was reporting was the latest stable (0.27.5).

**Comment by Daniel15** [comment] 2017-09-08 15:22
latest.tar.gz should always provide the stable version, not the RC. Unless
someone accidentally bumped the RC to stable :)

**Comment by mutuadavid93** [comment] 2020-04-23 09:57
Have done everything even followed heroku's guide but can't resolve my issue.
Here is my log.

```Enumerating objects: 205, done.
Counting objects: 100% (205/205), done.
Delta compression using up to 4 threads
Compressing objects: 100% (180/180), done.
Writing objects: 100% (205/205), 6.70 MiB | 1.50 MiB/s, done.
Total 205 (delta 36), reused 0 (delta 0)
remote: Compressing source files... done.
remote: Building source:
remote: 
remote: -----> Node.js app detected
remote:        
remote: -----> Creating runtime environment
remote:        
remote:        NPM_CONFIG_LOGLEVEL=error
remote:        NODE_ENV=production
remote:        NODE_MODULES_CACHE=true
remote:        NODE_VERBOSE=false
remote:        
remote: -----> Installing binaries
remote:        engines.node (package.json):  10.17.0
remote:        engines.npm (package.json):   6.11.3
remote:        engines.yarn (package.json):  1.19.2
remote:        
remote:        Resolving node version 10.17.0...
remote:        Downloading and installing node 10.17.0...
remote:        npm 6.11.3 already installed with node
remote:        Resolving yarn version 1.19.2...
remote:        Downloading and installing yarn (1.19.2)...
remote:        Installed yarn 1.19.2
remote:        
remote: -----> Installing dependencies
remote:        Installing node modules (yarn.lock)
remote:        yarn install v1.19.2
remote:        error An unexpected error occurred: "EROFS: read-only file system, mkdir '/home'".
remote:        info If you think this is a bug, please open a bug report with the information provided in "/tmp/build_950fd3a95fa3a5890ea1e883942b9a0d/yarn-error.log".
remote:        info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
remote: 
remote: -----> Build failed
remote:        
remote:        We're sorry this build is failing! You can troubleshoot common issues here:
remote:        https://devcenter.heroku.com/articles/troubleshooting-node-deploys
remote:        
remote:        If you're stuck, please submit a ticket so we can help:
remote:        https://help.heroku.com/
remote:        
remote:        Love,
remote:        Heroku
remote:        
remote:  !     Push rejected, failed to compile Node.js app.
remote: 
remote:  !     Push failed
remote: Verifying deploy...
remote: 
remote: !	Push rejected to safaricomplane.
remote: 
To https://git.heroku.com/safaricomplane.git
 ! [remote rejected] master -> master (pre-receive hook declined)```

**Comment by kjaisingh** [comment] 2020-07-21 04:16
Similar issue! Cannot be solved by any of the provided suggestions.
