### ISSUE TITLE
Yarn `--ignore-scripts` causing issues

### ISSUE THREAD

**Issue by OliverJAsh** [heroku/heroku-buildpack-nodejs#634] opened 2019-03-06 10:19 UTC
At Unsplash we use the popular tool [`patch-package`](https://github.com/ds300/patch-package) to apply patches to our Node modules after installation. This works in the form of a `postinstall` script.

However, this buildpack [invokes `yarn` with the `--ignore-scripts` flag when pruning dev dependencies](https://github.com/heroku/heroku-buildpack-nodejs/blob/v139/lib/dependencies.sh#L193) (since v119), which means `patch-package` will not run.

I can semi-understand why the buildpack would want to avoid invoking scripts, since the scripts were already run when `yarn` was invoked the first time, prior to building.

However, in this case we rely on scripts being invoked each time `yarn` is called, as they significantly modify the contents of `node_modules`. These modifications are needed for the app to run.

It feels like we need an option to opt-in to running scripts after pruning? Perhaps `YARN_PRUNE_SCRIPTS` 🤷‍♂️

**Comment by jmorrell** [comment] 2019-03-06 18:43
> I can semi-understand why the buildpack would want to avoid invoking scripts, since the scripts were already run when yarn was invoked the first time, prior to building.

This is needed because yarn does not provide a "prune" equivalent command. If someone were to kick off their build in `postinstall` they would end up running it twice, but it would fail the second time without `devDependencies`. The one we use was recommended in this issue: https://github.com/yarnpkg/yarn/issues/696

https://yarnpkg.com/lang/en/docs/cli/prune/

I'm hesitant to add another script to support a niche workflow like this. Would adding an option to skip the prune step and letting you control this in a `build` script work for you?

Hand-wavy:
```
  "build": "yarn prune && patch-package"
```

**Comment by danielleadams** [comment] 2020-01-07 18:52
Hi @OliverJAsh, were you able to resolve this and use the patch-package module?

**Comment by OliverJAsh** [comment] 2020-01-07 19:03
I think we just resolved to keep dev dependencies (i.e. disable pruning).

> Would adding an option to skip the prune step and letting you control this in a `build` script work for you?

Yeah I think so!

**Comment by OliverJAsh** [comment] 2020-03-17 16:52
> Would adding an option to skip the prune step and letting you control this in a `build` script work for you?

This should already be possible via `YARN_PRODUCTION="false"`, right?

**Comment by danielleadams** [comment] 2020-05-05 15:05
@OliverJAsh Sorry for the delay here. Yes, the buildpack will skip pruning with `YARN_PRODUCTION=false`, so that should fix your issue. This isn't ideal since now you aren't able to prune your dependencies.

Would adding a custom Heroku script at the end of the build be helpful? I think something like a `heroku-cleanup` would be helpful. I have been finding use cases where this would be helpful - so let me know what you think about this solution.

**Comment by OliverJAsh** [comment] 2020-05-05 17:07
That would be helpful. Another workaround I just thought it would be to run the cleanup in the `Procfile`, immediately before running the app.

**Comment by danielleadams** [comment] 2020-06-03 19:24
@OliverJAsh We've added a `heroku-cleanup` that runs after pruning and caching: https://devcenter.heroku.com/articles/nodejs-support#heroku-specific-build-steps. Please let me know if this solves your issue.

**Comment by danielleadams** [comment] 2020-06-11 17:30
Hi @OliverJAsh, just pinging again. I'd like to close this issue and want to make sure the solution we've provided fits the use case.

**Comment by OliverJAsh** [comment] 2020-06-11 17:33
Hi, sorry for missing your message. This is no longer a problem for us since we had to disable pruning of dev dependencies for other reasons, so I can't say whether it helps in our case, but maybe someone else who has faced this issue can help you?

**Comment by danielleadams** [comment] 2020-06-11 21:05
No problem - thanks for sharing. Going to go ahead and close this issue then.

**Closed by danielleadams** 2020-06-11 21:05 UTC
Labels: discussion, enhancement

**Comment by naiyt** [comment] 2020-11-28 04:39
Just stumbled on this issue, and I can confirm that the new build steps work great. In the context of `patch-package` I'm now doing this:

```
  "scripts": {
    "postinstall": "patch-package",
    "heroku-postbuild": "patch-package"
  }
```
