### ISSUE TITLE
Running tests incorrectly sets `NODE_ENV` to `production`

### ISSUE THREAD

**Issue by migueloller** [heroku/heroku-buildpack-nodejs#504] opened 2017-12-11 19:28 UTC
Moving over from gliderlabs/herokuish#309.

When running the Node.js buildpack `process.env.NODE_ENV` is set to `production` when it should be set to `test`.

Repro:

```bash
docker run -ti gliderlabs/herokuish

cat > app/package.json << EOF
{
  "name": "test",
  "version": "0.0.0",
  "scripts": {
    "test" "echo \$NODE_ENV"
  }
}
EOF

herokuish buildpack test
```

Interestingly, the execution logs indicate otherwise...

```
-----> Node.js app detected

-----> Creating runtime environment

       NPM_CONFIG_LOGLEVEL=error
       NPM_CONFIG_PRODUCTION=false
       NODE_VERBOSE=false
       NODE_ENV=test
       NODE_MODULES_CACHE=true

-----> Installing binaries
       engines.node (package.json):  unspecified
       engines.npm (package.json):   unspecified (use default)

       Resolving node version 6.x...
       Downloading and installing node 6.12.2...
       Using default npm version: 3.10.10

-----> Restoring cache
       Skipping cache restore (not-found)

-----> Building dependencies
       Installing node modules (package.json)

-----> Caching build
       Clearing previous node cache
       Saving 2 cacheDirectories (default):
       - node_modules
       - bower_components (nothing to cache)

-----> Build succeeded!
 !     This app may not specify any way to start a node process
       https://devcenter.heroku.com/articles/nodejs-support#default-web-process-type


> test@0.0.0 test /app
> echo $NODE_ENV

production
```

**Comment by jmorrell** [comment] 2017-12-12 01:20
This is probably a duplicate of #414, which I've not yet addressed. I'll take a look tomorrow.

**Comment by migueloller** [comment] 2017-12-12 01:24
@jmorrell, that workaround definitely works! Just wanted to report the issue 😄

**Comment by jmorrell** [comment] 2017-12-12 01:26
This issue had slipped my mind, so I appreciate the reminder 👍

**Closed** 2018-02-02 16:22 UTC

**Comment by gkatsanos** [comment] 2018-12-15 09:48
Hello, I guess I have the same issue, described there: https://stackoverflow.com/questions/53788097/using-a-separate-testing-mongo-database-on-mongo-and-heroku
My "test" command, even though it specifies NODE_ENV=test, seems to be running with production set.
```
    "test": "NODE_ENV=test nyc --reporter=html --reporter=text mocha --timeout 20000 --recursive src/tests",
```

**Comment by gkatsanos** [comment] 2018-12-20 22:47
@jmorrell hey Jeremy, any hints on what I could be doing wrong?
